/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumCoverLarge: typeof import('./src/components/AlbumCoverLarge.vue')['default']
    AlbumCoverSmall: typeof import('./src/components/AlbumCoverSmall.vue')['default']
    AlbumSelector: typeof import('./src/components/AlbumSelector.vue')['default']
    DateInput: typeof import('./src/components/DateInput.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconCarbonIsoOutline: typeof import('~icons/carbon/iso-outline')['default']
    IconTablerAperture: typeof import('~icons/tabler/aperture')['default']
    IconTablerArrowAutofitUp: typeof import('~icons/tabler/arrow-autofit-up')['default']
    IconTablerArrowsShuffle: typeof import('~icons/tabler/arrows-shuffle')['default']
    IconTablerBolt: typeof import('~icons/tabler/bolt')['default']
    IconTablerCalendar: typeof import('~icons/tabler/calendar')['default']
    IconTablerCamera: typeof import('~icons/tabler/camera')['default']
    IconTablerCameraRotate: typeof import('~icons/tabler/camera-rotate')['default']
    IconTablerCheckbox: typeof import('~icons/tabler/checkbox')['default']
    IconTablerCircleCheckFilled: typeof import('~icons/tabler/circle-check-filled')['default']
    IconTablerCircleDashedCheck: typeof import('~icons/tabler/circle-dashed-check')['default']
    IconTablerCircleDashedMinus: typeof import('~icons/tabler/circle-dashed-minus')['default']
    IconTablerClock: typeof import('~icons/tabler/clock')['default']
    IconTablerDownload: typeof import('~icons/tabler/download')['default']
    IconTablerEdit: typeof import('~icons/tabler/edit')['default']
    IconTablerEditOff: typeof import('~icons/tabler/edit-off')['default']
    IconTablerExclamationCircle: typeof import('~icons/tabler/exclamation-circle')['default']
    IconTablerEyePin: typeof import('~icons/tabler/eye-pin')['default']
    IconTablerHome: typeof import('~icons/tabler/home')['default']
    IconTablerLibraryPlus: typeof import('~icons/tabler/library-plus')['default']
    IconTablerMoonStars: typeof import('~icons/tabler/moon-stars')['default']
    IconTablerSettings: typeof import('~icons/tabler/settings')['default']
    IconTablerSquarePlus: typeof import('~icons/tabler/square-plus')['default']
    IconTablerSun: typeof import('~icons/tabler/sun')['default']
    IconTablerTags: typeof import('~icons/tabler/tags')['default']
    IconTablerTrash: typeof import('~icons/tabler/trash')['default']
    IconTablerTrashX: typeof import('~icons/tabler/trash-x')['default']
    IconTablerUpload: typeof import('~icons/tabler/upload')['default']
    IconTablerUser: typeof import('~icons/tabler/user')['default']
    IconTablerVinyl: typeof import('~icons/tabler/vinyl')['default']
    ImageSelector: typeof import('./src/components/ImageSelector.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    PhotoAlbums: typeof import('./src/components/PhotoAlbums.vue')['default']
    PhotoThumbnail: typeof import('./src/components/PhotoThumbnail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./src/components/Tag.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    TooltipIcon: typeof import('./src/components/TooltipIcon.vue')['default']
    ZoomableImage: typeof import('./src/components/ZoomableImage.vue')['default']
  }
}
